---
- name: Repository Configuration
  hosts: webservers
  tasks:
    - name: Ensure Example Repo exists
      ansible.builtin.yum_repository:
        name: example-internal
        description: Example Inc. Internal YUM repo
        file: example
        baseurl: http://ansible_client02/repos/
        gpgcheck: true

    - name: Ensure Repo RPM Key is Installed
      ansible.builtin.rpm_key:
        key: http://ansible_client02/repos/RPM-GPG-KEY-example
        state: present

    - name: Install rhelver package
      ansible.builtin.dnf:
        name: rhelver
        state: present
